package com.tomzem.cavealarm.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tomzem.cavealarm.bean.Alarm;

import com.tomzem.cavealarm.greendao.AlarmDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmDaoConfig;

    private final AlarmDao alarmDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmDaoConfig = daoConfigMap.get(AlarmDao.class).clone();
        alarmDaoConfig.initIdentityScope(type);

        alarmDao = new AlarmDao(alarmDaoConfig, this);

        registerDao(Alarm.class, alarmDao);
    }
    
    public void clear() {
        alarmDaoConfig.clearIdentityScope();
    }

    public AlarmDao getAlarmDao() {
        return alarmDao;
    }

}
